"""Finance jargon dictionary - 110 terms."""

FINANCE_JARGON: dict[str, str] = {
    "accrual": "recording income or expenses when they happen, not when cash moves",
    "amortization": "spreading the cost of something over time in regular payments",
    "annuity": "a series of equal payments made at regular intervals",
    "appreciation": "an increase in the value of an asset over time",
    "arbitrage": "profiting from price differences in different markets",
    "asset": "something of value that is owned, like cash, property, or investments",
    "audit": "an official review of financial records for accuracy",
    "balance sheet": "a snapshot of what a company owns and owes at a specific time",
    "basis point": "one hundredth of one percent, used to measure small rate changes",
    "bear market": "a period when stock prices are falling broadly",
    "benchmark": "a standard used to measure investment performance",
    "bond": "a loan to a company or government that pays interest over time",
    "bull market": "a period when stock prices are rising broadly",
    "capital": "money or assets available for investment or business use",
    "capital expenditure": "money spent on long-term assets like buildings or equipment",
    "capital gains": "profit made from selling an investment for more than you paid",
    "cash flow": "the movement of money in and out of a business",
    "collateral": "something pledged as security for a loan",
    "commodity": "a basic good like oil, gold, or wheat that is traded",
    "compound interest": "earning interest on both the original amount and previous interest",
    "contingent liability": "a potential debt that depends on a future event",
    "convertible bond": "a bond that can be exchanged for company stock",
    "cost basis": "the original price paid for an investment, used to calculate profit",
    "credit default swap": "an agreement that transfers the risk of a loan default",
    "credit rating": "a score showing how likely a borrower is to repay debts",
    "current ratio": "a measure of a company's ability to pay short-term debts",
    "debenture": "a type of bond not backed by specific assets",
    "debt-to-equity ratio": "how much a company borrows compared to what shareholders own",
    "default": "failing to make a required loan or debt payment",
    "deflation": "a general decrease in prices over time",
    "depreciation": "the gradual loss of value of an asset over time",
    "derivative": "a financial contract whose value depends on another asset",
    "diversification": "spreading investments across different types to reduce risk",
    "dividend": "a share of company profits paid to shareholders",
    "due diligence": "a thorough investigation before making a financial decision",
    "ebitda": "earnings before interest, taxes, depreciation, and amortization",
    "equity": "the value of ownership in a company or property",
    "escrow": "money held by a third party until conditions are met",
    "etf": "a fund that tracks an index and trades like a stock",
    "fiduciary": "a person legally required to act in another's financial interest",
    "fiscal year": "a 12-month period used for accounting, not always January to December",
    "fixed income": "investments that pay a set amount on a regular schedule",
    "float": "shares available for public trading",
    "foreclosure": "a lender seizing property when the borrower cannot pay",
    "futures contract": "an agreement to buy or sell something at a set price in the future",
    "gdp": "the total value of goods and services produced by a country",
    "goodwill": "the extra value a company has beyond its physical assets",
    "gross margin": "revenue minus the direct cost of goods sold",
    "hedge": "an investment made to reduce the risk of another investment",
    "hedge fund": "a private investment fund using advanced strategies",
    "illiquid": "difficult to sell or convert to cash quickly",
    "index fund": "a fund designed to match the performance of a market index",
    "inflation": "a general increase in prices over time",
    "initial public offering": "when a company first sells its stock to the public",
    "insolvency": "being unable to pay debts as they come due",
    "interest rate": "the percentage charged for borrowing money",
    "investment grade": "a rating indicating a bond is relatively safe",
    "ipo": "the first time a company sells stock to the public",
    "junk bond": "a high-risk bond that offers higher returns",
    "leverage": "using borrowed money to increase potential returns",
    "liability": "money or obligations that are owed",
    "libor": "a benchmark interest rate banks charge each other",
    "liquidation": "selling off assets to pay debts",
    "liquidity": "how easily an asset can be converted to cash",
    "long position": "buying an investment expecting its price to rise",
    "margin": "borrowing money from a broker to buy investments",
    "margin call": "a demand to add money when an investment account falls too low",
    "market capitalization": "the total value of a company's shares",
    "maturity": "the date when a loan or bond must be fully repaid",
    "merger": "two companies combining into one",
    "money market": "short-term, low-risk investments like treasury bills",
    "mortgage": "a loan used to buy property, with the property as security",
    "mutual fund": "a pool of money from many investors managed by professionals",
    "net asset value": "the total value of a fund's holdings divided by its shares",
    "net income": "total earnings after all expenses and taxes are paid",
    "operating expense": "the day-to-day costs of running a business",
    "option": "the right, but not obligation, to buy or sell at a set price",
    "overhead": "ongoing business costs not directly tied to making a product",
    "par value": "the face value of a bond or stock",
    "p/e ratio": "stock price divided by earnings per share",
    "portfolio": "a collection of investments owned by a person or organization",
    "premium": "the price paid for an insurance policy or option contract",
    "principal": "the original amount of money invested or borrowed",
    "private equity": "investment in companies not listed on public stock exchanges",
    "profit margin": "the percentage of revenue that becomes profit",
    "prospectus": "a document describing an investment opportunity",
    "quantitative easing": "a central bank buying assets to increase money supply",
    "rate of return": "the profit or loss on an investment expressed as a percentage",
    "recession": "a significant decline in economic activity lasting months",
    "refinance": "replacing an existing loan with a new one, often at better terms",
    "revenue": "the total income a business earns from sales",
    "risk tolerance": "how much financial uncertainty a person is comfortable with",
    "roi": "return on investment, measuring profit relative to cost",
    "securities": "tradable financial assets like stocks and bonds",
    "securitization": "bundling debts into a single product that can be sold",
    "share buyback": "a company purchasing its own stock from the market",
    "short selling": "selling borrowed stock hoping to buy it back at a lower price",
    "solvency": "the ability to meet long-term financial obligations",
    "spread": "the difference between two prices or interest rates",
    "stock split": "dividing existing shares into more shares at a lower price",
    "subprime": "lending to borrowers with poor credit at higher rates",
    "treasury bond": "a government bond considered very safe",
    "underwriting": "evaluating and taking on financial risk",
    "valuation": "estimating what a company or asset is worth",
    "venture capital": "money invested in early-stage companies with high growth potential",
    "volatility": "how much and how quickly prices change",
    "write-off": "removing a bad debt or loss from the books",
    "yield": "the income earned from an investment, usually as a percentage",
    "yield curve": "a graph showing interest rates for bonds of different lengths",
    "zero-coupon bond": "a bond that pays no interest but is sold at a discount",
}
