"""Legal jargon dictionary - 110 terms."""

LEGAL_JARGON: dict[str, str] = {
    "acquittal": "a court decision that a person is not guilty",
    "adjudicate": "to make a formal judgment or decision",
    "admissible": "allowed to be used as evidence in court",
    "affidavit": "a written statement made under oath",
    "allegation": "a claim that someone has done something wrong",
    "amicus curiae": "a person who advises the court but is not part of the case",
    "annulment": "a court ruling that a marriage was never valid",
    "appeal": "asking a higher court to review a decision",
    "arbitration": "settling a dispute outside of court with a neutral person",
    "arraignment": "a court hearing where charges are formally read",
    "bail": "money paid to get released from jail while awaiting trial",
    "bench trial": "a trial decided by a judge instead of a jury",
    "beyond reasonable doubt": "the high level of proof needed for a criminal conviction",
    "binding": "legally required to be followed",
    "breach": "breaking a law, rule, or agreement",
    "brief": "a written argument submitted to a court",
    "burden of proof": "the responsibility to prove a claim is true",
    "cease and desist": "a formal demand to stop doing something",
    "civil": "related to disputes between people, not criminal charges",
    "class action": "a lawsuit filed by a group of people with the same complaint",
    "clemency": "mercy or leniency shown by a court or authority",
    "codicil": "a change or addition to a will",
    "common law": "law based on past court decisions rather than written laws",
    "complainant": "the person who files a complaint or lawsuit",
    "contempt of court": "disrespecting or disobeying a court order",
    "continuance": "postponing a court proceeding to a later date",
    "conviction": "a formal declaration that someone is guilty",
    "corroborate": "to support or confirm with additional evidence",
    "damages": "money awarded to someone who was harmed",
    "de facto": "existing in reality even if not officially recognized",
    "de jure": "according to the law",
    "declaratory judgment": "a court ruling that states the rights of parties without ordering action",
    "decree": "a formal order issued by a court",
    "default judgment": "a ruling made when one side fails to respond",
    "defendant": "the person being accused or sued",
    "deposition": "sworn testimony given outside of court",
    "discovery": "the process of exchanging evidence before trial",
    "dismissal": "ending a case without a final decision",
    "docket": "the schedule or list of cases in a court",
    "double jeopardy": "being tried twice for the same crime",
    "due diligence": "a careful investigation before making a decision",
    "due process": "the fair treatment required by law",
    "easement": "the right to use someone else's land for a specific purpose",
    "emancipation": "freeing a minor from parental control",
    "eminent domain": "the government's power to take private property for public use",
    "encumbrance": "a claim or restriction on a property",
    "estoppel": "a rule that prevents someone from going back on their word",
    "exculpatory": "evidence that shows a person is not guilty",
    "executor": "the person who carries out the instructions in a will",
    "ex parte": "done for one side only, without the other side present",
    "extradition": "sending a person to another place to face charges",
    "felony": "a serious crime with a punishment of more than one year in prison",
    "fiduciary": "a person trusted to act in another's best interest",
    "force majeure": "an unforeseeable event that prevents fulfilling a contract",
    "foreclosure": "a lender taking property when the borrower cannot pay",
    "garnishment": "taking money from someone's wages to pay a debt",
    "grand jury": "a group that decides if there is enough evidence to charge someone",
    "habeas corpus": "a legal demand to bring a prisoner before a court",
    "hearsay": "secondhand information not allowed as evidence in court",
    "immunity": "protection from prosecution or legal action",
    "incarceration": "being put in prison",
    "indemnity": "protection against loss or damage, often through payment",
    "indictment": "a formal charge of a serious crime",
    "injunction": "a court order to do or stop doing something",
    "in loco parentis": "acting in place of a parent",
    "intellectual property": "creations of the mind protected by law, such as inventions",
    "interrogatory": "written questions one side must answer under oath",
    "judgment": "the final decision of a court",
    "jurisdiction": "the authority of a court to hear a case",
    "jurisprudence": "the study and theory of law",
    "larceny": "stealing someone's personal property",
    "liability": "legal responsibility for something",
    "lien": "a legal claim on property as security for a debt",
    "litigation": "the process of taking legal action in court",
    "malfeasance": "wrongdoing or illegal actions by a public official",
    "mandate": "an official order or command",
    "mediation": "using a neutral person to help settle a dispute",
    "misdemeanor": "a minor crime, usually punished with less than one year in jail",
    "mitigating circumstances": "facts that may reduce the severity of a punishment",
    "moot": "no longer relevant or worth debating",
    "motion": "a formal request made to a court",
    "negligence": "failure to take reasonable care, causing harm",
    "nolo contendere": "a plea of no contest, not admitting guilt",
    "notarize": "to officially certify a document",
    "objection": "a formal protest in court about a question or evidence",
    "ordinance": "a local law passed by a city or county",
    "parole": "early release from prison with conditions",
    "perjury": "lying under oath in court",
    "plaintiff": "the person who starts a lawsuit",
    "plea bargain": "an agreement to plead guilty to a lesser charge",
    "power of attorney": "legal authority to act on someone else's behalf",
    "precedent": "a past court decision used as a guide for future cases",
    "pro bono": "legal work done for free",
    "probate": "the legal process of handling a deceased person's estate",
    "probation": "supervised release instead of prison time",
    "prosecute": "to bring criminal charges against someone",
    "quash": "to reject or void a legal action",
    "recusal": "a judge removing themselves from a case due to bias",
    "remand": "sending a case back to a lower court",
    "restitution": "paying back money or returning property to the victim",
    "retainer": "a fee paid in advance to secure a lawyer's services",
    "statute": "a written law passed by a legislature",
    "statute of limitations": "the deadline for filing a legal claim",
    "subpoena": "a legal order to appear in court or provide evidence",
    "tort": "a wrongful act that leads to a civil lawsuit",
    "verdict": "the decision of a jury or judge",
    "waiver": "voluntarily giving up a legal right",
    "warrant": "a court order allowing police to take an action",
    "writ": "a formal written order issued by a court",
    "zoning": "local rules about how land can be used",
}
