"""Medical jargon dictionary - 110 terms."""

MEDICAL_JARGON: dict[str, str] = {
    "abrasion": "a scrape on the skin",
    "acute": "sudden and severe, but usually short-lasting",
    "adenoma": "a non-cancerous tumor in a gland",
    "adverse event": "an unwanted side effect or bad reaction",
    "afebrile": "having no fever",
    "analgesic": "a painkiller",
    "anaphylaxis": "a severe, life-threatening allergic reaction",
    "anemia": "low red blood cell count, causing tiredness",
    "angina": "chest pain caused by reduced blood flow to the heart",
    "antibiotic": "a medicine that kills bacteria",
    "arrhythmia": "an irregular heartbeat",
    "asymptomatic": "showing no symptoms",
    "atrophy": "shrinking or wasting away of body tissue",
    "benign": "not cancerous, not harmful",
    "bilateral": "on both sides of the body",
    "biopsy": "removing a small piece of tissue to test for disease",
    "bradycardia": "a slower-than-normal heart rate",
    "carcinoma": "a type of cancer that starts in the skin or organ lining",
    "cardiac": "related to the heart",
    "catheter": "a thin tube inserted into the body",
    "chronic": "long-lasting, ongoing",
    "coagulation": "blood clotting",
    "comorbidity": "having two or more medical conditions at the same time",
    "contraindication": "a reason not to use a certain treatment",
    "contusion": "a bruise",
    "ct scan": "a detailed X-ray that takes pictures from many angles",
    "cyanosis": "bluish skin color from lack of oxygen",
    "debridement": "removing dead or damaged tissue from a wound",
    "diagnosis": "identifying what illness or condition someone has",
    "dialysis": "a machine filtering the blood when kidneys cannot",
    "distal": "farther from the center of the body",
    "dysphagia": "difficulty swallowing",
    "dyspnea": "shortness of breath",
    "echocardiogram": "an ultrasound of the heart",
    "edema": "swelling caused by fluid buildup",
    "embolism": "a blood clot blocking a blood vessel",
    "endemic": "regularly found in a certain area or population",
    "epidemiology": "the study of how diseases spread",
    "etiology": "the cause or origin of a disease",
    "febrile": "having a fever",
    "fibrillation": "rapid, irregular heart rhythm",
    "fracture": "a broken bone",
    "gastric": "related to the stomach",
    "hematoma": "a solid swelling of clotted blood",
    "hemorrhage": "heavy bleeding",
    "hepatic": "related to the liver",
    "hypertension": "high blood pressure",
    "hypotension": "low blood pressure",
    "hypoxia": "low oxygen levels in the body",
    "idiopathic": "arising from an unknown cause",
    "immunocompromised": "having a weakened immune system",
    "infarction": "death of tissue due to blocked blood supply",
    "inflammation": "redness, swelling, and pain as the body heals",
    "inpatient": "a patient who stays in the hospital",
    "intubation": "inserting a tube into the windpipe to help breathing",
    "ischemia": "reduced blood flow to a body part",
    "laceration": "a deep cut or tear in the skin",
    "lesion": "an area of damaged tissue",
    "malignant": "cancerous and likely to spread",
    "metastasis": "cancer spreading from one body part to another",
    "morbidity": "the state of being ill or unhealthy",
    "mortality": "death rate",
    "mri": "a scan using magnets to create detailed body images",
    "necrosis": "death of body tissue",
    "neoplasm": "an abnormal growth or tumor",
    "neuropathy": "nerve damage causing pain, numbness, or weakness",
    "nosocomial": "an infection caught in a hospital",
    "occlusion": "a blockage",
    "oncology": "the study and treatment of cancer",
    "orthopedic": "related to bones and joints",
    "outpatient": "a patient who visits but does not stay overnight",
    "palpation": "examining the body by touch",
    "pathogen": "a germ that causes disease",
    "perfusion": "blood flow through tissue",
    "platelet": "a blood cell that helps clotting",
    "pneumonia": "an infection that inflames the air sacs in the lungs",
    "prognosis": "the expected outcome of an illness",
    "prophylaxis": "treatment to prevent disease",
    "proximal": "closer to the center of the body",
    "pulmonary": "related to the lungs",
    "renal": "related to the kidneys",
    "resection": "surgical removal of part of an organ",
    "respiratory": "related to breathing",
    "sepsis": "a dangerous body-wide infection response",
    "stenosis": "narrowing of a passage in the body",
    "subcutaneous": "under the skin",
    "symptom": "a sign of illness felt by the patient",
    "syndrome": "a group of symptoms that occur together",
    "tachycardia": "a faster-than-normal heart rate",
    "thrombosis": "a blood clot inside a blood vessel",
    "titration": "gradually adjusting a drug dose",
    "toxicology": "the study of poisons and their effects",
    "triage": "sorting patients by urgency of treatment needed",
    "tumor": "an abnormal mass of tissue",
    "ulcer": "an open sore on the skin or inside the body",
    "ultrasound": "imaging using sound waves",
    "vascular": "related to blood vessels",
    "ventilator": "a machine that helps a patient breathe",
    "vital signs": "basic body measurements like heart rate and temperature",
    "auscultation": "listening to body sounds with a stethoscope",
    "diuretic": "a medicine that helps the body get rid of extra fluid",
    "emetic": "something that causes vomiting",
    "hemoglobin": "the protein in red blood cells that carries oxygen",
    "immunoglobulin": "an antibody protein that fights infections",
    "palliative": "treatment focused on comfort, not curing",
    "remission": "a period when symptoms decrease or disappear",
    "sequela": "a condition caused by an earlier illness",
    "sputum": "mucus coughed up from the lungs",
    "suture": "stitches used to close a wound",
    "transfusion": "putting donated blood into a patient",
}
