"""Tech jargon dictionary - 110 terms."""

TECH_JARGON: dict[str, str] = {
    "abstraction": "hiding complex details behind a simpler interface",
    "agile": "a flexible approach to building software in small steps",
    "algorithm": "a step-by-step set of instructions to solve a problem",
    "api": "a way for different software programs to talk to each other",
    "authentication": "verifying that a user is who they claim to be",
    "authorization": "checking what a user is allowed to do",
    "backend": "the behind-the-scenes part of a program that handles data",
    "bandwidth": "the amount of data that can be sent over a connection",
    "binary": "a system using only two values, 0 and 1",
    "blockchain": "a shared digital record that is very hard to change",
    "boolean": "a value that is either true or false",
    "bot": "a program that performs automated tasks",
    "branch": "a separate copy of code for making changes without affecting the main version",
    "browser": "a program for viewing websites",
    "bug": "a mistake in software that causes it to behave incorrectly",
    "cache": "a temporary storage area for quick access to frequently used data",
    "ci/cd": "automatically testing and releasing software updates",
    "cli": "a text-based way to interact with a computer",
    "cloud": "storing and accessing data over the internet instead of locally",
    "cluster": "a group of computers working together as one system",
    "codebase": "all the source code files for a software project",
    "compiler": "a tool that converts human-readable code into machine instructions",
    "container": "a lightweight package that includes everything needed to run software",
    "cors": "a security rule about which websites can share data with each other",
    "cpu": "the main chip in a computer that runs instructions",
    "crud": "the four basic data operations: create, read, update, delete",
    "css": "the language used to style the appearance of web pages",
    "daemon": "a background program that runs without user interaction",
    "database": "an organized collection of data stored electronically",
    "debug": "finding and fixing errors in software",
    "deploy": "releasing software so users can access it",
    "dependency": "a piece of software that another program needs to work",
    "deprecated": "still working but no longer recommended for use",
    "devops": "practices that combine software development and IT operations",
    "dns": "the system that translates website names into numerical addresses",
    "docker": "a tool for packaging software into portable containers",
    "dom": "the structure of a web page that programs can read and change",
    "encryption": "scrambling data so only authorized people can read it",
    "endpoint": "a specific address where a service can be accessed",
    "environment variable": "a setting stored outside the code that controls program behavior",
    "ethernet": "a way to connect computers using cables",
    "firewall": "a security system that controls incoming and outgoing network traffic",
    "firmware": "permanent software built into a hardware device",
    "framework": "a pre-built set of tools for building software faster",
    "frontend": "the part of a program that users see and interact with",
    "full stack": "working on both the user-facing and behind-the-scenes parts",
    "function": "a reusable block of code that performs a specific task",
    "git": "a tool for tracking changes to code over time",
    "gpu": "a chip designed for fast image processing and parallel tasks",
    "gui": "a visual interface with buttons and windows for interacting with software",
    "hash": "a fixed-length code generated from data, used for verification",
    "hostname": "the name that identifies a computer on a network",
    "html": "the language used to create the structure of web pages",
    "http": "the rules for sending data between a browser and a website",
    "https": "a secure version of HTTP that encrypts data in transit",
    "ide": "a program that provides tools for writing and testing code",
    "immutable": "something that cannot be changed after it is created",
    "indexing": "organizing data so it can be searched quickly",
    "infrastructure": "the underlying systems that support software, like servers and networks",
    "instance": "a single running copy of a program or service",
    "interpreter": "a tool that runs code line by line without compiling first",
    "ip address": "a unique number that identifies a device on a network",
    "iteration": "repeating a process, often improving each time",
    "json": "a common text format for storing and exchanging data",
    "kernel": "the core part of an operating system that manages hardware",
    "kubernetes": "a system for managing and running containers at scale",
    "latency": "the delay between a request and a response",
    "library": "a collection of pre-written code that developers can reuse",
    "load balancer": "a system that distributes work across multiple servers",
    "localhost": "a way to refer to the computer you are currently using",
    "machine learning": "teaching computers to learn patterns from data",
    "malware": "harmful software designed to damage or exploit systems",
    "merge": "combining changes from different code branches",
    "metadata": "data that describes other data",
    "microservice": "a small, independent service that does one specific job",
    "middleware": "software that connects different applications together",
    "migration": "moving data or systems from one place to another",
    "monolith": "a single large program where everything is tightly connected",
    "mutex": "a lock that prevents two processes from using the same resource",
    "namespace": "a container that keeps names organized to avoid conflicts",
    "nginx": "a popular web server and load balancer",
    "node": "a single computer or device in a network",
    "oauth": "a standard for letting apps access user data without sharing passwords",
    "open source": "software whose code is freely available for anyone to use or modify",
    "orm": "a tool that lets code work with databases using regular objects",
    "packet": "a small chunk of data sent over a network",
    "patch": "a small update that fixes a problem in software",
    "pipeline": "a series of automated steps for processing data or code",
    "port": "a numbered channel on a computer for network communication",
    "protocol": "a set of rules for how data is sent between systems",
    "proxy": "a server that acts as a go-between for requests",
    "pull request": "a request to review and merge code changes",
    "query": "a request for specific information from a database",
    "queue": "a line of tasks waiting to be processed in order",
    "ram": "temporary memory a computer uses while running programs",
    "refactor": "reorganizing code to make it cleaner without changing what it does",
    "regex": "a pattern used to search and match text",
    "repository": "a storage location for code and its history",
    "rest api": "a common style for building web services that exchange data",
    "rollback": "undoing a change and going back to a previous version",
    "runtime": "the period when a program is actually running",
    "saas": "software accessed over the internet as a subscription",
    "sandbox": "an isolated environment for testing without affecting real systems",
    "scalability": "the ability of a system to handle more work as demand grows",
    "sdk": "a toolkit for building software for a specific platform",
    "server": "a computer that provides services to other computers",
    "ssh": "a secure way to connect to and control another computer remotely",
    "ssl": "a security standard for encrypting data sent over the internet",
    "stack trace": "a list showing where an error happened in the code",
    "tcp": "a reliable method for sending data between computers",
    "token": "a piece of data used to verify identity or grant access",
    "webhook": "an automatic notification sent when an event happens",
}
